# Generated by Django 2.2 on 2019-04-21 22:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='race',
            old_name='fouth',
            new_name='fourth',
        ),
        migrations.AlterField(
            model_name='race',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='racer',
            name='class_r',
            field=models.CharField(choices=[('4', 'Fourth'), ('3', 'Third'), ('2', 'Second'), ('1', 'First')], default='fo', help_text="Choose the racer's class", max_length=1, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='desc_c',
            field=models.CharField(help_text="Enter the car's description", max_length=1000, verbose_name='Car'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='desc_r',
            field=models.CharField(help_text="Enter the racer's description", max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='exp_r',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Experienced'), ('P', 'Professional')], default='b', help_text="Choose the racer's experience", max_length=1, verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Identifier'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='name_r',
            field=models.CharField(help_text="Enter the racer's name", max_length=200, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='name_t',
            field=models.CharField(help_text="Enter the team's name", max_length=200, verbose_name='Team'),
        ),
    ]
