# Generated by Django 2.2 on 2019-04-21 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20190422_0144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='racer',
            name='class_r',
            field=models.CharField(choices=[('4', 'Fourth'), ('3', 'Third'), ('2', 'Second'), ('1', 'First')], default='fo', help_text="Choose the racer's class", max_length=1, verbose_name='Class'),
        ),
        migrations.AlterField(
            model_name='racer',
            name='exp_r',
            field=models.CharField(choices=[('B', 'Beginner'), ('I', 'Intermediate'), ('E', 'Experienced'), ('P', 'Professional')], default='b', help_text="Choose the racer's experience", max_length=1, verbose_name='Experience'),
        ),
    ]
