# Generated by Django 2.2 on 2019-04-21 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20190422_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='race',
            name='fifth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer_fifth', to='board.Racer', unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='first',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer_first', to='board.Racer', unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='fourth',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer_fourth', to='board.Racer', unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='second',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer_second', to='board.Racer', unique=True),
        ),
        migrations.AlterField(
            model_name='race',
            name='third',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='racer_third', to='board.Racer', unique=True),
        ),
    ]
