# Generated by Django 2.2 on 2019-04-22 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0010_comment_commenter'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='type',
            field=models.CharField(choices=[('0', 'Other'), ('1', 'Question about the race'), ('2', 'Collaboration inquiry')], default='0', max_length=1, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race', to='board.Race', verbose_name='race'),
        ),
    ]
