# Generated by Django 2.2 on 2019-04-22 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_auto_20190422_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commenter_id', to=settings.AUTH_USER_MODEL, verbose_name='commenter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='race',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='race_id', to='board.Race', verbose_name='race'),
        ),
    ]
